// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ButtonRepo: typeof import('./src/components/ButtonRepo.vue')['default']
    HeaderMain: typeof import('./src/components/HeaderMain.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskDay: typeof import('./src/components/tasks/TaskDay.vue')['default']
    TaskItem: typeof import('./src/components/tasks/TaskItem.vue')['default']
  }
}
